name: Make EPG 
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Download WebGrab+Plus
      run: |
        wget http://webgrabplus.com/sites/default/files/download/SW/V3.2.0/WebGrabPlus_V3.2_install.tar.gz
    - name: Extract WebGrabPlus_V3.2_install.tar.gz
      run: |
        tar -zxvf WebGrabPlus_V3.2_install.tar.gz
    - name: Install WebGrab+Plus
      run: |
        cd .wg++
        ./install.sh
    - name: Download WebGrab++.config.xml
      run: |
        cd .wg++
        wget -N https://raw.githubusercontent.com/LiuYi0526/IPTV/master/WebGrab++.config.xml
    - name: Run
      run: |
        cd .wg++
        ./run.sh
    - name: Download Other EPG
      run: |
        cd .wg++
        wget https://raw.githubusercontent.com/bebawy6/EPG/master/usEPG.xml
        wget https://xmltvfr.fr/xmltv/xmltv.xml
        # wget https://epgshare01.online/epgshare01/epg_ripper_US_SPORTS1.xml.gz
        # gunzip ./epg_ripper_US_SPORTS1.xml.gz
    - name: Install xmltv
      run: |
        sudo apt update
        sudo apt -y install xmltv
    - name: Merge EPG
      run: |
        cd .wg++
        tv_cat guide.xml xmltv.xml > part1.xml
        tv_cat part1.xml epg.xml > part2.xml
        tv_cat part2.xml malaysia.xml > last_part.xml
        tv_cat last_part.xml usEPG.xml > guide_merge.xml
    - name : Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: guide.xml
        path: .wg++/guide.xml
    - name: Git push assets to "EPG" branch
      run: |
        cd .wg++
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b EPG
        git add .
        git commit -m "Update EPG"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin EPG
