# This is a basic workflow to help you get started with Actions

name: euronews

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 4,16 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.5.3
      
      - name: Main
        run: |
          pwd
          cd scripts
          python3 euronews.py > ../euronews.m3u8
          echo "m3u grabbed"
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "links are updated"
          git push
